# Generated by Django 4.2 on 2024-12-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='наименование')),
                ('state', models.CharField(choices=[('1', 'создана'), ('2', 'товар передан в доставку'), ('3', 'товар доставлен')], default='1', max_length=1, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
                'ordering': ('pk',),
            },
        ),
    ]
